### ISSUE TITLE
Required Perspective Empty

### ISSUE THREAD

**Issue by ghost** [rynop/ggreplayz#9]
Both in Opera (12) and FF(14) on Win7 I find the "Perspective" drop down empty.  Cannot submit, replay details are populated.

**Comment by rynop** [comment]
Can you provide me a link where I can download the .SC2Replay file, so I can dig into the problem?

**Comment by ghost** [comment]
http://drop.sc/241241

**Comment by ghost** [comment]
Here is another one with the same problem.  http://drop.sc/241769

**Comment by sunealoneal** [comment]
I have this issue as well. Chrome 21 on Windows 7. I can't continue process because I need to fill out those boxes but they are empty.

http://drop.sc/242716

**Comment by rynop** [comment]
Thanks for reporting.  The format of the replay file changed with patch 1.5.  I have pushed a fix, things should be working now - please re-open if you find more problems.
